"""Add DailyJournal model

Revision ID: 2d6b6de3290b
Revises: 50d0cf5e90dc
Create Date: 2026-07-09 10:45:38.946304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6b6de3290b'
down_revision: Union[str, Sequence[str], None] = '50d0cf5e90dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journals',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('food_logs', sa.JSON(), nullable=False),
    sa.Column('habits', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('water_ml', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_daily_journals_date'), 'daily_journals', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journals_date'), table_name='daily_journals')
    op.drop_table('daily_journals')
    # ### end Alembic commands ###
