"""Modular refactor with micros and supplements

Revision ID: 50d0cf5e90dc
Revises: 3fe1be0708f5
Create Date: 2026-07-09 09:21:02.425100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d0cf5e90dc'
down_revision: Union[str, Sequence[str], None] = '3fe1be0708f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_logs_id'), 'supplement_logs', ['id'], unique=False)
    op.create_index(op.f('ix_supplement_logs_name'), 'supplement_logs', ['name'], unique=False)
    op.add_column('food_logs', sa.Column('micros', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_logs', 'micros')
    op.drop_index(op.f('ix_supplement_logs_name'), table_name='supplement_logs')
    op.drop_index(op.f('ix_supplement_logs_id'), table_name='supplement_logs')
    op.drop_table('supplement_logs')
    # ### end Alembic commands ###
