"""add meal_catalog and supplement_catalog tables

Revision ID: ace7b68444e2
Revises: ba094835959f
Create Date: 2026-07-17 11:31:33.942803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace7b68444e2'
down_revision: Union[str, Sequence[str], None] = 'ba094835959f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_catalog',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('meal_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('yield_g', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('addons', sa.JSON(), nullable=True),
    sa.Column('default_addon_ids', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_catalog_id'), 'meal_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_meal_catalog_name'), 'meal_catalog', ['name'], unique=False)
    op.create_table('supplement_catalog',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('default_dose', sa.Float(), nullable=True),
    sa.Column('default_time_of_day', sa.String(length=20), nullable=True),
    sa.Column('micros', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplement_catalog_id'), 'supplement_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_supplement_catalog_name'), 'supplement_catalog', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplement_catalog_name'), table_name='supplement_catalog')
    op.drop_index(op.f('ix_supplement_catalog_id'), table_name='supplement_catalog')
    op.drop_table('supplement_catalog')
    op.drop_index(op.f('ix_meal_catalog_name'), table_name='meal_catalog')
    op.drop_index(op.f('ix_meal_catalog_id'), table_name='meal_catalog')
    op.drop_table('meal_catalog')
    # ### end Alembic commands ###
