"""Add micros_sum for Firestore optimization

Revision ID: c1fbe6c436a6
Revises: 2d6b6de3290b
Create Date: 2026-07-10 07:24:04.990724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fbe6c436a6'
down_revision: Union[str, Sequence[str], None] = '2d6b6de3290b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_journals', sa.Column('micros_sum', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_journals', 'micros_sum')
    # ### end Alembic commands ###
